
#include "led.h"

void LED_Control(u8 led_ctrl)
{

	HAL_GPIO_WritePin(GPIOC,0xff00,GPIO_PIN_SET);	
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_SET);	
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_RESET);	
	

	HAL_GPIO_WritePin(GPIOC,led_ctrl<<8,GPIO_PIN_RESET);
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_SET);	
	HAL_GPIO_WritePin(GPIOD,GPIO_PIN_2,GPIO_PIN_RESET);	
}
